version: "3"

services:
  proxy:
    restart: always
    image: nginx:latest
    networks: 
      - external_network
    #- internal_network
    # Mapping host ports 80 and 443 into the Nginx service directly
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/tmp:/var/run/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/rootdir:/usr/share/nginx/html
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    command: [ nginx-debug, '-g', 'daemon off;' ]

  certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

  wordpress1:
    restart: always
    image: wordpress:6.1-apache
    environment:
      WORDPRESS_DB_HOST: 'db'
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'password1234'
      WORDPRESS_DB_NAME: 'wordpress'
    networks:
      - external_network
    volumes:
      - ./wordpress:/var/www/html

  wordpress2:
    restart: always
    image: wordpress:6.1-apache
    environment:
      WORDPRESS_DB_HOST: 'db'
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'password1234'
      WORDPRESS_DB_NAME: 'wordpress'
    networks:
      - external_network
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'password1234'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - external_network
    volumes:
      - ./mysql/wordpress:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    #command:
    #  - "--loglevel"
    #  - "verbose"
    restart: always
    networks:
      - external_network


networks:
  external_network:
  internal_network:
    internal: true

