version: "3"

services:
  proxy:
    restart: always
    image: nginx:latest
#   shm-size: 256mb
    networks: 
      - internal_network
      - external_network
    # Mapping host ports 80 and 443 into the Nginx service directly
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/tmp:/var/run/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
#     - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/rootdir:/rootdir
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'password1234'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - internal_network
    ports:
      - 3306:3306
    volumes:
      - ./mysql/wordpress:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

networks:
  external_network:
  internal_network:
    internal: true


#redis:
#   container_name: "${COMPOSE_PROJECT_NAME}-redis"
#   image: redis:latest
#   ports:
#     - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"

